language: ruby
rvm:
#  - 1.8.7
  - ree
#  - 1.9.3

env:
#  - RAILS_VERSION=3-0-stable
  - RAILS_VERSION=3-1-stable
#  - RAILS_VERSION=3-2-stable

notifications:
  recipients:
    - alexey@kovyrin.net

script: script/cruise_build

# whitelist branches
branches:
  only:
    - master
    - rails2x
