#!/bin/bash

# Making the script more robust
set -e # Exit on errors
set -u # Exit on uninitialized variables

# Test environment
export RAILS_ENV=test

# Install gems
bundle install --deployment --without development test

# Configure database access
cp -f config/database.yml.example config/database.yml

# Vendor the plugin
rm -rf vendor/plugins/db-charmer vendor/db-charmer
git clone git://github.com/kovyrin/db-charmer.git vendor/db-charmer

# Create databases and sharding tables
mysql -u root < db/create_databases.sql
mysql -u root db_charmer_sandbox_test < db/sharding.sql

# Run migrations
bundle exec rake db:migrate

# Run the build and return its exit code
exec bundle exec rake spec
