#!/bin/bash

# Making the script more robust
set -e # Exit on errors
set -u # Exit on uninitialized variables

# Test environment
export RAILS_ENV=test

# Vendor the gem
mkdir -p vendor
rm -rf vendor/plugins/db-charmer vendor/db-charmer
ln -s ../../db-charmer vendor/db-charmer

# Install gems
bundle install --deployment --without development test

# Configure database access
cp -f config/database.yml.example config/database.yml

# Create databases and sharding tables
mysql -u root < db/create_databases.sql
mysql -u root db_charmer_sandbox_test < db/sharding.sql

# Run migrations
bundle exec rake db:migrate

# Run the build and return its exit code
exec bundle exec rake spec
